name = "Modfest: Carnival"
author = "ModFest"
version = "0.24.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a1dd788157fce69383ac14f1751596e737065da56b7726ae0d446934a4a1b1c"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
