name: Pull mod data from ModFest platform

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This script does not have any dependencies, so a pip install is not needed
      - name: Build pack
        run: python scripts/pull_platform.py
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Pull platform data